/**
 * ApprovalGate — two-step human approval workflow with stepper integration.
 *
 * Phases: idle → confirming → approved → executing → done | rejected | error
 *
 * Safety guarantees enforced here:
 *   - Execution button disabled until a safe candidate is selected
 *   - Backend /approve re-validates safety before recording intent
 *   - Backend /execute requires pending approval token (one-use)
 *   - Confirmation dialog explicitly says "simulated execution"
 *   - Duplicate submission prevented by phase state machine
 *
 * Post-maneuver verification section shown after execution.
 * Incident report displayed when generated by backend.
 *
 * Human-supervised decision-support prototype. Simulation only — not flight software.
 */
import { useState, useRef, useEffect } from 'react'
import { apiPost } from '../api/client'

export default function ApprovalGate({
  scenarioId, selectedId, analysis, onReset, onStepChange,
}) {
  const [phase, setPhase]           = useState('idle')
  const [execResult, setExecResult] = useState(null)
  const [report, setReport]         = useState(null)
  const [err, setErr]               = useState('')
  const confirmRef                  = useRef(null)

  const candidate = analysis?.candidates?.find(c => c.candidate_id === selectedId)

  // Focus confirmation dialog when it appears
  useEffect(() => {
    if (phase === 'confirming' && confirmRef.current) {
      confirmRef.current.focus()
    }
  }, [phase])

  if (!candidate) {
    return (
      <div className="action-bar">
        <span className="action-hint" aria-live="polite">
          Select a safe candidate from the maneuver table to enable approval.
        </span>
      </div>
    )
  }

  async function handleApprove() {
    setPhase('confirming')
    onStepChange?.('approve')
  }

  async function handleConfirm() {
    setErr('')
    setPhase('approved')
    onStepChange?.('simulate')
    try {
      // Step 1: Record approval — backend re-validates safety
      const res = await apiPost(`/scenarios/${scenarioId}/approve`, {
        scenario_id: scenarioId,
        candidate_id: selectedId,
        operator_id: 'OPERATOR',
      })
      if (!res.safety_gate_passed) {
        setPhase('rejected')
        setErr(res.rejection_reason ?? 'Safety gate rejected this candidate.')
        onStepChange?.('approve')
        return
      }

      // Step 2: Simulated execution
      setPhase('executing')
      const execRes = await apiPost(`/scenarios/${scenarioId}/execute`, {
        scenario_id: scenarioId,
        candidate_id: selectedId,
        operator_id: 'OPERATOR',
      })
      setExecResult(execRes)
      setPhase('done')
      onStepChange?.('verify')

      // Step 3: Request incident report (non-fatal)
      try {
        const rep = await apiPost(`/scenarios/${scenarioId}/incident-report`, {
          scenario_id: scenarioId,
          candidate_id: selectedId,
          operator_id: 'OPERATOR',
        })
        setReport(rep)
        onStepChange?.('report')
      } catch (_) { /* non-fatal — report is supplementary */ }

    } catch (e) {
      setErr(e.message)
      setPhase('error')
    }
  }

  function handleCancel() {
    setPhase('idle')
    onStepChange?.('approve')
  }

  function handleReset() {
    setPhase('idle')
    setExecResult(null)
    setReport(null)
    setErr('')
    onReset()
  }

  // Safety: never allow execution without explicit backend approval
  const canApprove = candidate?.is_safe === true && phase === 'idle'

  // ── IDLE ──────────────────────────────────────────────
  if (phase === 'idle') {
    return (
      <div>
        <div className="action-bar">
          <button
            className="btn btn-warn"
            disabled={!canApprove}
            onClick={handleApprove}
            aria-label={
              !canApprove
                ? 'Cannot approve: selected candidate is not safe'
                : `Request simulated execution of ${candidate.label}`
            }
          >
            Request Simulated Execution
          </button>
          <button
            className="btn btn-ghost"
            onClick={handleReset}
            aria-label="Reset workflow and deselect candidate"
          >
            Reset
          </button>
          {!canApprove && (
            <span className="action-hint" aria-live="polite">
              {candidate?.is_safe === false
                ? 'This candidate was rejected by the safety gate — select a safe candidate.'
                : 'Candidate safety status unknown.'}
            </span>
          )}
        </div>

        {/* Selected candidate summary */}
        {candidate && (
          <div
            style={{
              marginTop: '0.75rem',
              padding: '0.6rem 0.75rem',
              background: 'var(--surface2)',
              border: '1px solid var(--border)',
              borderRadius: 'var(--radius-md)',
              fontSize: '0.7rem',
              color: 'var(--text-dim)',
            }}
            aria-label="Selected candidate summary"
          >
            <strong style={{ color: 'var(--accent)' }}>Selected:</strong>{' '}
            {candidate.label} — Δv {candidate.delta_v_ms?.toFixed(2)} m/s
            {candidate.fuel_cost_kg != null && ` · Fuel ${candidate.fuel_cost_kg.toFixed(4)} kg`}
            {candidate.post_maneuver_miss_distance_km != null &&
              ` · Post-miss ${candidate.post_maneuver_miss_distance_km.toFixed(3)} km`}
          </div>
        )}
      </div>
    )
  }

  // ── CONFIRMING ────────────────────────────────────────
  if (phase === 'confirming') {
    return (
      <div
        className="confirm-dialog"
        role="dialog"
        aria-modal="true"
        aria-labelledby="confirm-title"
        aria-describedby="confirm-desc"
        tabIndex={-1}
        ref={confirmRef}
      >
        <h3 id="confirm-title">
          <span aria-hidden="true">⚠</span> Confirm Simulated Execution
        </h3>
        <p id="confirm-desc">
          You are about to approve <strong>{candidate.label}</strong> ({selectedId})
          for <strong>simulated execution</strong>.
        </p>

        {/* Maneuver summary grid */}
        <div className="confirm-kv-grid" aria-label="Maneuver summary">
          <div className="confirm-kv">
            <span className="k">Candidate ID</span>
            <span className="v">{selectedId}</span>
          </div>
          <div className="confirm-kv">
            <span className="k">Direction</span>
            <span className="v">{candidate.direction ?? 'Not provided'}</span>
          </div>
          <div className="confirm-kv">
            <span className="k">Delta-v</span>
            <span className="v">{candidate.delta_v_ms?.toFixed(2)} m/s</span>
          </div>
          <div className="confirm-kv">
            <span className="k">Est. fuel</span>
            <span className="v">
              {candidate.fuel_cost_kg != null ? candidate.fuel_cost_kg.toFixed(4) + ' kg' : 'Not provided'}
            </span>
          </div>
          <div className="confirm-kv">
            <span className="k">Post-maneuver miss</span>
            <span className="v">
              {candidate.post_maneuver_miss_distance_km != null
                ? candidate.post_maneuver_miss_distance_km.toFixed(3) + ' km'
                : 'Not provided'}
            </span>
          </div>
          <div className="confirm-kv">
            <span className="k">Safety gate</span>
            <span className="v" style={{ color: 'var(--green)' }}>Passed ✓</span>
          </div>
        </div>

        {/* Explicit simulation disclaimer */}
        <div className="sim-warning" role="alert">
          ⚠ SIMULATION ONLY — not flight software. No spacecraft will be commanded.
          This is a prototype demonstration.
        </div>

        <div className="action-bar">
          <button
            className="btn btn-danger"
            onClick={handleConfirm}
            aria-label="Confirm and submit simulated execution to backend"
          >
            Confirm — Simulate Execution
          </button>
          <button
            className="btn btn-ghost"
            onClick={handleCancel}
            aria-label="Cancel and return to selection"
          >
            Cancel
          </button>
        </div>
      </div>
    )
  }

  // ── PROCESSING ────────────────────────────────────────
  if (phase === 'approved' || phase === 'executing') {
    return (
      <div
        style={{ display: 'flex', alignItems: 'center', gap: '0.6rem', color: 'var(--text-dim)', fontSize: '0.8rem' }}
        aria-live="polite"
        aria-busy="true"
      >
        <span className="spinner" aria-hidden="true" />
        {phase === 'approved' ? 'Submitting approval to backend…' : 'Simulating execution…'}
      </div>
    )
  }

  // ── DONE ──────────────────────────────────────────────
  if (phase === 'done' && execResult) {
    const verificationResolved = execResult.post_maneuver_miss_distance_km != null &&
      execResult.post_maneuver_miss_distance_km > (analysis?.conjunction_threshold_km ?? 1.0)

    return (
      <div>
        {/* Execution result */}
        <div className="exec-result" role="region" aria-label="Simulated execution result">
          <h3>Simulated Execution Complete</h3>
          <div className="exec-kv">
            <span className="k">Status</span>
            <span className="v">{execResult.status}</span>
          </div>
          <div className="exec-kv">
            <span className="k">Candidate applied</span>
            <span className="v">{execResult.candidate_id}</span>
          </div>
          <div className="exec-kv">
            <span className="k">Delta-v applied</span>
            <span className="v">
              {execResult.delta_v_applied_ms != null
                ? execResult.delta_v_applied_ms.toFixed(2) + ' m/s'
                : 'Not provided'}
            </span>
          </div>
          <div className="exec-kv">
            <span className="k">Fuel consumed</span>
            <span className="v">
              {execResult.fuel_consumed_kg != null
                ? execResult.fuel_consumed_kg.toFixed(4) + ' kg'
                : 'Not provided'}
            </span>
          </div>
          <div className="exec-kv">
            <span className="k">Post-maneuver miss distance</span>
            <span
              className="v"
              style={{
                color: verificationResolved ? 'var(--green)' : 'var(--yellow)',
              }}
            >
              {execResult.post_maneuver_miss_distance_km != null
                ? execResult.post_maneuver_miss_distance_km.toFixed(3) + ' km'
                : 'Not provided'}
            </span>
          </div>
          <div className="exec-kv">
            <span className="k">Executed at (UTC)</span>
            <span className="v">
              {execResult.executed_at
                ? new Date(execResult.executed_at).toUTCString()
                : 'Not provided'}
            </span>
          </div>
          {execResult.execution_label && (
            <div
              style={{ marginTop: '0.55rem', fontSize: '0.62rem', color: 'var(--yellow)' }}
              role="note"
            >
              {execResult.execution_label}
            </div>
          )}
        </div>

        {/* Post-maneuver verification panel */}
        <div
          className="verification-panel"
          role="region"
          aria-label="Post-maneuver verification"
        >
          <h4>Post-Maneuver Verification</h4>
          <div className="exec-kv">
            <span className="k">New miss distance</span>
            <span className="v">
              {execResult.post_maneuver_miss_distance_km != null
                ? execResult.post_maneuver_miss_distance_km.toFixed(3) + ' km'
                : 'Not provided'}
            </span>
          </div>
          <div className="exec-kv">
            <span className="k">Conjunction threshold</span>
            <span className="v">{analysis?.conjunction_threshold_km ?? '1.0'} km</span>
          </div>
          <div className="exec-kv">
            <span className="k">Resolution status</span>
            <span
              className="v"
              style={{ color: verificationResolved ? 'var(--green)' : 'var(--yellow)' }}
            >
              {execResult.post_maneuver_miss_distance_km == null
                ? 'Not provided'
                : verificationResolved
                ? '✓ Resolved — miss distance exceeds threshold'
                : '⚠ Monitor — still within watch area'}
            </span>
          </div>
          <div className="exec-kv">
            <span className="k">Verification source</span>
            <span className="v">Backend deterministic evaluation</span>
          </div>
          <div
            style={{ marginTop: '0.5rem', fontSize: '0.62rem', color: 'var(--muted)', fontStyle: 'italic' }}
            role="note"
          >
            Verification is based on simulated state-vector perturbation.
            Not derived from real post-maneuver tracking.
          </div>
        </div>

        {/* Incident report */}
        {report && (
          <div className="incident-section" role="region" aria-label="Incident report">
            <div className="incident-header">
              <span>Incident Report</span>
              <span style={{ color: 'var(--muted)', textTransform: 'none', fontWeight: 400 }}>
                Generated by: {report.generated_by}
                {report.generated_by === 'granite' && ' (IBM Granite)'}
                {report.generated_by !== 'granite' && ' (deterministic template)'}
              </span>
            </div>
            <pre className="incident-report" aria-label="Incident report text">
              {report.report_text}
            </pre>
          </div>
        )}

        <div className="action-bar" style={{ marginTop: '0.85rem' }}>
          <button
            className="btn btn-ghost"
            onClick={handleReset}
            aria-label="Reset and start a new analysis"
          >
            New Analysis
          </button>
        </div>
      </div>
    )
  }

  // ── REJECTED ──────────────────────────────────────────
  if (phase === 'rejected') {
    return (
      <div className="exec-result rejected" role="alert">
        <h3>Safety Gate: Execution Rejected</h3>
        <p style={{ fontSize: '0.72rem', marginTop: '0.4rem', color: 'var(--red)' }}>
          {err || 'Safety gate rejected this candidate. Select a different safe candidate.'}
        </p>
        <div className="action-bar" style={{ marginTop: '0.75rem' }}>
          <button className="btn btn-ghost" onClick={handleReset}>Reset</button>
        </div>
      </div>
    )
  }

  // ── ERROR ─────────────────────────────────────────────
  if (phase === 'error') {
    return (
      <div className="exec-result rejected" role="alert">
        <h3>Backend Error</h3>
        <p style={{ fontSize: '0.72rem', marginTop: '0.4rem', color: 'var(--text-dim)' }}>
          {err || 'An error occurred during execution.'}
        </p>
        <div className="action-bar" style={{ marginTop: '0.75rem' }}>
          <button className="btn btn-ghost" onClick={() => setPhase('idle')}>Retry</button>
          <button className="btn btn-ghost" onClick={handleReset}>Reset</button>
        </div>
      </div>
    )
  }

  return null
}
